pyuic5 "window_main.ui" -x -o "ui_window_main.py"
pyuic5 "widget_newsfeed_search.ui" -x -o "ui_widget_newsfeed_search.py"
pyuic5 "widget_photos_search.ui" -x -o "ui_widget_photos_search.py"
pyuic5 "widget_video_search.ui" -x -o "ui_widget_video_search.py"
pyuic5 "widget_get_users.ui" -x -o "ui_widget_get_users.py"
pyrcc5 "resources.qrc" -o "resources_rc.py"