# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\parsing_inf_from_social_networks\vk_parser\widget_newsfeed_search.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Newsfeed_Search(object):
    def setupUi(self, MainWindow_Newsfeed_Search):
        MainWindow_Newsfeed_Search.setObjectName("MainWindow_Newsfeed_Search")
        MainWindow_Newsfeed_Search.resize(300, 317)
        self.centralwidget = QtWidgets.QWidget(MainWindow_Newsfeed_Search)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_newsfeed_search = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_newsfeed_search.setGeometry(QtCore.QRect(10, 10, 281, 301))
        self.groupBox_newsfeed_search.setObjectName("groupBox_newsfeed_search")
        self.pushButton_newsfeed_search_clear = QtWidgets.QPushButton(self.groupBox_newsfeed_search)
        self.pushButton_newsfeed_search_clear.setGeometry(QtCore.QRect(80, 230, 71, 23))
        self.pushButton_newsfeed_search_clear.setObjectName("pushButton_newsfeed_search_clear")
        self.groupBox_newsfeed_search_time = QtWidgets.QGroupBox(self.groupBox_newsfeed_search)
        self.groupBox_newsfeed_search_time.setGeometry(QtCore.QRect(10, 140, 261, 81))
        self.groupBox_newsfeed_search_time.setObjectName("groupBox_newsfeed_search_time")
        self.groupBox_newsfeed_search_start_time = QtWidgets.QGroupBox(self.groupBox_newsfeed_search_time)
        self.groupBox_newsfeed_search_start_time.setGeometry(QtCore.QRect(10, 20, 120, 51))
        self.groupBox_newsfeed_search_start_time.setObjectName("groupBox_newsfeed_search_start_time")
        self.lineEdit_newsfeed_search_start_time_year = QtWidgets.QLineEdit(self.groupBox_newsfeed_search_start_time)
        self.lineEdit_newsfeed_search_start_time_year.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.lineEdit_newsfeed_search_start_time_year.setObjectName("lineEdit_newsfeed_search_start_time_year")
        self.lineEdit_newsfeed_search_start_time_day = QtWidgets.QLineEdit(self.groupBox_newsfeed_search_start_time)
        self.lineEdit_newsfeed_search_start_time_day.setGeometry(QtCore.QRect(10, 20, 21, 20))
        self.lineEdit_newsfeed_search_start_time_day.setObjectName("lineEdit_newsfeed_search_start_time_day")
        self.lineEdit_newsfeed_search_start_time_month = QtWidgets.QLineEdit(self.groupBox_newsfeed_search_start_time)
        self.lineEdit_newsfeed_search_start_time_month.setGeometry(QtCore.QRect(40, 20, 21, 20))
        self.lineEdit_newsfeed_search_start_time_month.setObjectName("lineEdit_newsfeed_search_start_time_month")
        self.groupBox_newsfeed_search_end_time = QtWidgets.QGroupBox(self.groupBox_newsfeed_search_time)
        self.groupBox_newsfeed_search_end_time.setGeometry(QtCore.QRect(130, 20, 120, 51))
        self.groupBox_newsfeed_search_end_time.setObjectName("groupBox_newsfeed_search_end_time")
        self.lineEdit_newsfeed_search_end_time_month = QtWidgets.QLineEdit(self.groupBox_newsfeed_search_end_time)
        self.lineEdit_newsfeed_search_end_time_month.setGeometry(QtCore.QRect(40, 20, 21, 20))
        self.lineEdit_newsfeed_search_end_time_month.setObjectName("lineEdit_newsfeed_search_end_time_month")
        self.lineEdit_newsfeed_search_end_time_year = QtWidgets.QLineEdit(self.groupBox_newsfeed_search_end_time)
        self.lineEdit_newsfeed_search_end_time_year.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.lineEdit_newsfeed_search_end_time_year.setObjectName("lineEdit_newsfeed_search_end_time_year")
        self.lineEdit_newsfeed_search_end_time_day = QtWidgets.QLineEdit(self.groupBox_newsfeed_search_end_time)
        self.lineEdit_newsfeed_search_end_time_day.setGeometry(QtCore.QRect(10, 20, 21, 20))
        self.lineEdit_newsfeed_search_end_time_day.setObjectName("lineEdit_newsfeed_search_end_time_day")
        self.lineEdit_newsfeed_search_q = QtWidgets.QLineEdit(self.groupBox_newsfeed_search)
        self.lineEdit_newsfeed_search_q.setGeometry(QtCore.QRect(10, 39, 261, 21))
        self.lineEdit_newsfeed_search_q.setObjectName("lineEdit_newsfeed_search_q")
        self.pushButton_newsfeed_search_load = QtWidgets.QPushButton(self.groupBox_newsfeed_search)
        self.pushButton_newsfeed_search_load.setGeometry(QtCore.QRect(10, 230, 71, 23))
        self.pushButton_newsfeed_search_load.setObjectName("pushButton_newsfeed_search_load")
        self.label_7 = QtWidgets.QLabel(self.groupBox_newsfeed_search)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_7.setObjectName("label_7")
        self.groupBox_newsfeed_search_geotag = QtWidgets.QGroupBox(self.groupBox_newsfeed_search)
        self.groupBox_newsfeed_search_geotag.setGeometry(QtCore.QRect(10, 70, 261, 71))
        self.groupBox_newsfeed_search_geotag.setObjectName("groupBox_newsfeed_search_geotag")
        self.lineEdit_newsfeed_search_latitude = QtWidgets.QLineEdit(self.groupBox_newsfeed_search_geotag)
        self.lineEdit_newsfeed_search_latitude.setGeometry(QtCore.QRect(10, 39, 111, 21))
        self.lineEdit_newsfeed_search_latitude.setObjectName("lineEdit_newsfeed_search_latitude")
        self.label_8 = QtWidgets.QLabel(self.groupBox_newsfeed_search_geotag)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_newsfeed_search_longitude = QtWidgets.QLineEdit(self.groupBox_newsfeed_search_geotag)
        self.lineEdit_newsfeed_search_longitude.setGeometry(QtCore.QRect(140, 39, 111, 21))
        self.lineEdit_newsfeed_search_longitude.setObjectName("lineEdit_newsfeed_search_longitude")
        self.label_9 = QtWidgets.QLabel(self.groupBox_newsfeed_search_geotag)
        self.label_9.setGeometry(QtCore.QRect(140, 20, 111, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_newsfeed_search_save = QtWidgets.QPushButton(self.groupBox_newsfeed_search)
        self.pushButton_newsfeed_search_save.setGeometry(QtCore.QRect(230, 270, 41, 21))
        self.pushButton_newsfeed_search_save.setObjectName("pushButton_newsfeed_search_save")
        self.lineEdit_newsfeed_search_file_name = QtWidgets.QLineEdit(self.groupBox_newsfeed_search)
        self.lineEdit_newsfeed_search_file_name.setGeometry(QtCore.QRect(10, 270, 211, 21))
        self.lineEdit_newsfeed_search_file_name.setText("")
        self.lineEdit_newsfeed_search_file_name.setObjectName("lineEdit_newsfeed_search_file_name")
        self.lineEdit_newsfeed_search_status = QtWidgets.QLineEdit(self.groupBox_newsfeed_search)
        self.lineEdit_newsfeed_search_status.setEnabled(False)
        self.lineEdit_newsfeed_search_status.setGeometry(QtCore.QRect(160, 230, 111, 21))
        self.lineEdit_newsfeed_search_status.setObjectName("lineEdit_newsfeed_search_status")
        MainWindow_Newsfeed_Search.setCentralWidget(self.centralwidget)
        self.action_6 = QtWidgets.QAction(MainWindow_Newsfeed_Search)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow_Newsfeed_Search)
        self.action_7.setObjectName("action_7")

        self.retranslateUi(MainWindow_Newsfeed_Search)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Newsfeed_Search)

    def retranslateUi(self, MainWindow_Newsfeed_Search):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Newsfeed_Search.setWindowTitle(_translate("MainWindow_Newsfeed_Search", "MainWindow"))
        self.groupBox_newsfeed_search.setTitle(_translate("MainWindow_Newsfeed_Search", "Поиск по постам, новостям, записям"))
        self.pushButton_newsfeed_search_clear.setText(_translate("MainWindow_Newsfeed_Search", "Очистка"))
        self.groupBox_newsfeed_search_time.setTitle(_translate("MainWindow_Newsfeed_Search", "Дата"))
        self.groupBox_newsfeed_search_start_time.setTitle(_translate("MainWindow_Newsfeed_Search", "Не ранее"))
        self.groupBox_newsfeed_search_end_time.setTitle(_translate("MainWindow_Newsfeed_Search", "Не позже"))
        self.pushButton_newsfeed_search_load.setText(_translate("MainWindow_Newsfeed_Search", "Загрузка"))
        self.label_7.setText(_translate("MainWindow_Newsfeed_Search", "Строка запроса"))
        self.groupBox_newsfeed_search_geotag.setTitle(_translate("MainWindow_Newsfeed_Search", "Геотаг"))
        self.label_8.setText(_translate("MainWindow_Newsfeed_Search", "N-широта д.дробь"))
        self.label_9.setText(_translate("MainWindow_Newsfeed_Search", "E-долгота д.дробь"))
        self.pushButton_newsfeed_search_save.setText(_translate("MainWindow_Newsfeed_Search", "Save"))
        self.lineEdit_newsfeed_search_status.setText(_translate("MainWindow_Newsfeed_Search", "Данных нет"))
        self.action_6.setText(_translate("MainWindow_Newsfeed_Search", "Создать новую базу"))
        self.action_7.setText(_translate("MainWindow_Newsfeed_Search", "Загрузить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_Newsfeed_Search = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Newsfeed_Search()
    ui.setupUi(MainWindow_Newsfeed_Search)
    MainWindow_Newsfeed_Search.show()
    sys.exit(app.exec_())
